// Route Parameters
POST http://localhost:3333/songs
Content-Type: application/json

{
    "title": "ATE THAT",
    "artist_id": "YOUNG POSSE",
    "album_id": "ATE THAT EP",
    "genre": "hiphop",
    "duration": 3,
    "url": "https://open.spotify.com/track/6spCL6M22BQACNDd70Gov3?si=824b8f8c0e1e4b34"
}

###
GET http://localhost:3333/songs

###
PUT http://localhost:3333/songs/
Content-Type: application/json

###
DELETE http://localhost:3333/songs/899e5605-c324-4008-9be4-e87e680c9ec3

// Query Parameters
###
GET http://localhost:3333/songs?search=

