// Route Parameters
POST http://localhost:3333/songs
Content-Type: application/json

{
    "title": "",
    "artist_ID": "",
    "album_ID": "",
    "genre": "",
    "duration": ,
    "url": ""
}

###
GET http://localhost:3333/songs

###
PUT http://localhost:3333/songs/
Content-Type: application/json

###
DELETE http://localhost:3333/songs/

// Query Parameters
###
GET http://localhost:3333/songs?search=

