// Route Parameters
POST http://localhost:3333/songs
Content-Type: application/json

{
    "title": "Freak On a Leash",
    "artist_ID": "Korn",
    "album_ID": "Follow The Leader",
    "genre": "rock",
    "duration": 415,
    "url": "https://open.spotify.com/track/6W21LNLz9Sw7sUSNWMSHRu?si=c141c46e52ae46dc"
}

###
GET http://localhost:3333/songs

###
PUT http://localhost:3333/songs/
Content-Type: application/json

###
DELETE http://localhost:3333/songs/

// Query Parameters
###
GET http://localhost:3333/songs?search=

